version: "3.9"

services:
  db:
    image: mysql:8.0.32
    container_name: db
    condition: service_healthy
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=senhaSegura
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    working_dir: /app-backend
    command: dev
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      # Os dados abaixo se referem ao container `db`
      - DB_USER=root
      - DB_PASS=senhaSegura
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5