# Usar a imagem node:16.14-alpine como base
FROM node:16.14-alpine 
# Mudar para o diretório de trabalho /app-backend
WORKDIR /app-backend
# Copia os package.json, package-lock.json e packages.npm para o container
COPY package*.json ./
# Instalar as dependências Node
RUN npm install

# Copia o restante dos arquivos da aplicação para o container
COPY . .
# Expõe a porta 3001
EXPOSE 3001

# Configurar os comandos para iniciar a aplicação de acordo com as boas práticas
ENTRYPOINT [ "npm", "run" ]

CMD [ "start" ]